//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int CTHoaDon_ID { get; set; }
        public int HoaDon_ID { get; set; }
        public int MonAn_ID { get; set; }
        public int ChiTietHD_SoLuong { get; set; }
        public int ChiTietHD_DonGia { get; set; }
        public string ChiTietHD_GhiChu { get; set; }
        public string ChiTietHD_TrangThai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
