//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonNhap
    {
        public int CTDonNhap_ID { get; set; }
        public int DonNhap_ID { get; set; }
        public int NL_ID { get; set; }
        public int ChiTietDon_SoLuong { get; set; }
        public string ChiTietDon_DonViTinh { get; set; }
        public decimal ChiTietDon_DonGia { get; set; }
        public decimal ChiTietDon_ThanhTien { get; set; }
    
        public virtual DonNhapNguyenLieu DonNhapNguyenLieu { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
