//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMonAn
    {
        public int CTMonAn_ID { get; set; }
        public int MonAn_ID { get; set; }
        public int NL_ID { get; set; }
        public int ChiTietMonAn_SoLuong { get; set; }
        public string ChiTietMonAn_DonViTinh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
