//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocUong
    {
        public int Nuoc_ID { get; set; }
        public string Nuoc_Ten { get; set; }
        public string Nuoc_DonViTinh { get; set; }
        public string Nuoc_HinhAnh { get; set; }
        public decimal Nuoc_Gia { get; set; }
        public string Nuoc_TrangThai { get; set; }
    }
}
